FROM flatfish

ENV USERNAME $USER
ENV UUID $UUID
ENV UGID $UGID

RUN useradd -m $USER && \
    echo "$USER:$USER" | chpasswd && \
    usermod --shell /bin/bash $USER && \
    usermod -aG sudo $USER && \
    echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/$USER && \
    chmod 0440 /etc/sudoers.d/$USER

RUN usermod  --uid $UUID $USER && \
    groupmod --gid $UGID $USER; exit 0

CMD ["/usr/sbin/sshd", "-D"]
